#pragma once

#if defined(__has_include)
#if __has_include(<zmk/lvgl_compat.h>)
#include <zmk/lvgl_compat.h>
#else
#ifdef LV_LVGL_H_INCLUDE_SIMPLE
#include "lvgl.h"
#else
#include <lvgl.h>
#endif
#if defined(LVGL_VERSION_MAJOR) && LVGL_VERSION_MAJOR >= 9
#ifndef LV_IMG_CF_TRUE_COLOR
#define LV_IMG_CF_TRUE_COLOR LV_COLOR_FORMAT_NATIVE
#endif
#ifndef LV_IMG_CF_TRUE_COLOR_ALPHA
#define LV_IMG_CF_TRUE_COLOR_ALPHA LV_COLOR_FORMAT_NATIVE_WITH_ALPHA
#endif
#ifndef LV_IMG_CF_TRUE_COLOR_CHROMA_KEYED
#define LV_IMG_CF_TRUE_COLOR_CHROMA_KEYED LV_COLOR_FORMAT_NATIVE
#endif
#ifndef LV_IMG_CF_INDEXED_1BIT
#define LV_IMG_CF_INDEXED_1BIT LV_COLOR_FORMAT_I1
#endif
#ifndef LV_IMG_CF_INDEXED_2BIT
#define LV_IMG_CF_INDEXED_2BIT LV_COLOR_FORMAT_I2
#endif
#ifndef LV_IMG_CF_INDEXED_4BIT
#define LV_IMG_CF_INDEXED_4BIT LV_COLOR_FORMAT_I4
#endif
#ifndef LV_IMG_CF_INDEXED_8BIT
#define LV_IMG_CF_INDEXED_8BIT LV_COLOR_FORMAT_I8
#endif
#ifndef LV_IMG_CF_ALPHA_1BIT
#define LV_IMG_CF_ALPHA_1BIT LV_COLOR_FORMAT_A1
#endif
#ifndef LV_IMG_CF_ALPHA_2BIT
#define LV_IMG_CF_ALPHA_2BIT LV_COLOR_FORMAT_A2
#endif
#ifndef LV_IMG_CF_ALPHA_4BIT
#define LV_IMG_CF_ALPHA_4BIT LV_COLOR_FORMAT_A4
#endif
#ifndef LV_IMG_CF_ALPHA_8BIT
#define LV_IMG_CF_ALPHA_8BIT LV_COLOR_FORMAT_A8
#endif
#ifndef LV_IMG_CF_RAW
#define LV_IMG_CF_RAW LV_COLOR_FORMAT_RAW
#endif
#ifndef LV_IMG_CF_RAW_ALPHA
#define LV_IMG_CF_RAW_ALPHA LV_COLOR_FORMAT_RAW_ALPHA
#endif
#ifndef LV_IMG_CF_RAW_CHROMA_KEYED
#define LV_IMG_CF_RAW_CHROMA_KEYED LV_COLOR_FORMAT_RAW
#endif
#endif
#endif
#else /* __has_include not available */
#ifdef LV_LVGL_H_INCLUDE_SIMPLE
#include "lvgl.h"
#else
#include <lvgl.h>
#endif
#if defined(LVGL_VERSION_MAJOR) && LVGL_VERSION_MAJOR >= 9
#ifndef LV_IMG_CF_TRUE_COLOR
#define LV_IMG_CF_TRUE_COLOR LV_COLOR_FORMAT_NATIVE
#endif
#ifndef LV_IMG_CF_TRUE_COLOR_ALPHA
#define LV_IMG_CF_TRUE_COLOR_ALPHA LV_COLOR_FORMAT_NATIVE_WITH_ALPHA
#endif
#ifndef LV_IMG_CF_TRUE_COLOR_CHROMA_KEYED
#define LV_IMG_CF_TRUE_COLOR_CHROMA_KEYED LV_COLOR_FORMAT_NATIVE
#endif
#ifndef LV_IMG_CF_INDEXED_1BIT
#define LV_IMG_CF_INDEXED_1BIT LV_COLOR_FORMAT_I1
#endif
#ifndef LV_IMG_CF_INDEXED_2BIT
#define LV_IMG_CF_INDEXED_2BIT LV_COLOR_FORMAT_I2
#endif
#ifndef LV_IMG_CF_INDEXED_4BIT
#define LV_IMG_CF_INDEXED_4BIT LV_COLOR_FORMAT_I4
#endif
#ifndef LV_IMG_CF_INDEXED_8BIT
#define LV_IMG_CF_INDEXED_8BIT LV_COLOR_FORMAT_I8
#endif
#ifndef LV_IMG_CF_ALPHA_1BIT
#define LV_IMG_CF_ALPHA_1BIT LV_COLOR_FORMAT_A1
#endif
#ifndef LV_IMG_CF_ALPHA_2BIT
#define LV_IMG_CF_ALPHA_2BIT LV_COLOR_FORMAT_A2
#endif
#ifndef LV_IMG_CF_ALPHA_4BIT
#define LV_IMG_CF_ALPHA_4BIT LV_COLOR_FORMAT_A4
#endif
#ifndef LV_IMG_CF_ALPHA_8BIT
#define LV_IMG_CF_ALPHA_8BIT LV_COLOR_FORMAT_A8
#endif
#ifndef LV_IMG_CF_RAW
#define LV_IMG_CF_RAW LV_COLOR_FORMAT_RAW
#endif
#ifndef LV_IMG_CF_RAW_ALPHA
#define LV_IMG_CF_RAW_ALPHA LV_COLOR_FORMAT_RAW_ALPHA
#endif
#ifndef LV_IMG_CF_RAW_CHROMA_KEYED
#define LV_IMG_CF_RAW_CHROMA_KEYED LV_COLOR_FORMAT_RAW
#endif
#endif
#endif
